import { NextResponse } from "next/server";
import { db } from "@/lib/db";

// GET /api/cases/[id]/export — exports a resolved case as a Markdown case study.
// This satisfies the hackathon optional deliverable:
// "Alert case study or review log".
export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const c = await db.case.findUnique({
    where: { id },
    include: {
      alert: { include: { agent: true, provider: true } },
      events: { orderBy: { createdAt: "asc" } },
    },
  });
  if (!c) return NextResponse.json({ error: "case not found" }, { status: 404 });

  const a = c.alert;
  let evidence: any = {};
  try {
    evidence = JSON.parse(a.evidence);
  } catch {
    /* ignore */
  }

  const fmt = (d: Date) => d.toISOString().replace("T", " ").substring(0, 19) + " UTC";

  const md = `# Case Study: ${a.title}

> **SALI — Super Agent Liquidity & Risk Intelligence Platform**
> Codex Community Hackathon · bKash presents SUST CSE Carnival 2026
> **Synthetic data only — no real customer, agent, or account referenced.**

---

## Case Summary

| Field | Value |
|-------|-------|
| Case ID | \`${c.id}\` |
| Alert ID | \`${a.id}\` |
| Status | **${c.status}** |
| Priority | ${c.priority.toUpperCase()} |
| Severity | ${a.severity} |
| Type | ${a.type} |
| Category | ${a.category} |
| Scenario | ${a.scenarioTag ?? "—"} |
| Owner | ${c.ownerName ?? "Unassigned"} (${c.ownerRole}) |
| Created | ${fmt(c.createdAt)} |
| Resolved | ${c.resolvedAt ? fmt(c.resolvedAt) : "—"} |

## Agent & Provider

- **Agent:** ${a.agent.name} (\`${a.agent.code}\`)
- **Location:** ${a.agent.area}, ${a.agent.thana}, ${a.agent.district}
- **Provider:** ${a.provider?.name ?? "Shared cash / cross-provider"}

## Alert Message

${a.message}

${a.messageBn ? `### বাংলা বার্তা\n\n${a.messageBn}\n` : ""}
## Evidence

${evidence.facts ? `### Facts\n\n| Label | Value |\n|-------|-------|\n${evidence.facts.map((f: any) => `| ${f.label} | ${f.value} |`).join("\n")}\n` : ""}
${evidence.possibleNormalReasons ? `### Possible Normal Reasons\n\n${evidence.possibleNormalReasons.map((r: string) => `- ${r}`).join("\n")}\n` : ""}
${evidence.uncertainty ? `### Uncertainty\n\n${evidence.uncertainty}\n` : ""}
${evidence.safeNextStep ? `### Safe Next Step\n\n${evidence.safeNextStep}\n` : ""}
${evidence.falsePositiveNote ? `### False-Positive Note\n\n${evidence.falsePositiveNote}\n` : ""}

## Confidence

- **Score:** ${Math.round(a.confidence * 100)}%
- **Label:** ${a.confidenceLabel}

## Escalation Path

${JSON.parse(c.escalationPath ?? "[]").map((r: string, i: number) => `${i + 1}. ${r}${r === c.ownerRole ? " (owner)" : ""}`).join("\n")}

## Coordination Audit Trail

| Time | Event | Actor | Role | Note |
|------|-------|-------|------|------|
${c.events.map((e) => `| ${fmt(e.createdAt)} | ${e.type} | ${e.actor} | ${e.role} | ${e.note ?? ""} |`).join("\n")}

---

## Responsible-Design Note

- This case study uses **synthetic data only** — no real customer identities, credentials, or accounts.
- The anomaly signal is **advisory** — it does not declare fraud. Human review was required before any action.
- The prototype **did not execute** any real financial transaction, block, freeze, or transfer.
- Provider boundaries were **preserved** — no cross-provider balance conversion or unauthorized access.

---

*Generated by SALI on ${fmt(new Date())}*
`;

  return new NextResponse(md, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="case-${c.id.slice(-8)}.md"`,
    },
  });
}
